### ISSUE TITLE
Save search state in query params

### ISSUE THREAD

**Issue by shifty11** [skiff-org/skiff-apps#151]
**Is your feature request related to a problem? Please describe.**
It is quite annoying to use the search and then loose the state after a searched item has been clicked. This occures when going back to the previous page (via browser back button). Since I have this button on my mouse I use it all the time in my browser to go back and forth on webpages.

Current workflow:
- I search my mails
- I click on a searched mail and read it
- I click the back button
- I am back on the inbox

**Describe the solution you'd like**
- I search my mails
- I click on a searched mail and read it
- I click the back button
- I expect that I am back on the list with my search (not working)

If the state would be saved in query params it would also allow users to save links to a specific searches.

**Comment by amilich** [comment]
> @shifty11 Kindly assign this issue to me.

done

**Comment by Drex72** [comment]
@shifty11 , Since this issue still isnt solved, could i be assigned to this issue and work on it?
